### ISSUE TITLE
CLI commands are incorrectly async

### ISSUE THREAD

**Issue by tari** [zigpy/bellows#128]
Some CLI commands are incorrectly declared as `async def`, which causes them to do nothing, and Python prints a warning on exit that nothing waited on the coroutine.

The ones I've tested firsthand exhibiting this behavior are `form` and `permit`. Changing `async def` to just `def` fixes the problem- `util.app` handles the event loop itself, so the CLI commands taking this form should not be declared async.

**Comment by AndreasBomholtz** [comment]
Thanks you for reporting this. 
Can you make a pull request with the fixes?
