### ISSUE TITLE
Suggestion: Rename bellows to "zigpy-bellows" (alternativly to "zigpy-ezsp" or similar)

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#140]
I like to suggest to rename the bellows library to "zigpy-bellows" in order for following the same naming convention as the zigpy-xbee and zigpy-deconz libraries (as well as zigpy-zigate). I think that this would give a better indication that this library is specifically meant to be used with by zigpy project. 

Again similar naming convention as the zigpy-deconz and zigpy-xbee libraries:
- https://github.com/zigpy/zigpy-xbee
- https://github.com/zigpy/zigpy-deconz

Also the new ZiGate library for zigpy follow this naming standard scheme:
- https://github.com/doudz/zigpy-zigate

Maybe even take a library renaming opportunity to rename bellows to "zigpy-ezsp" or ""zigpy-emberznet" to show that the library is for the EZSP protocol / EmberZNet stack, so more similarly named after how the zigpy-xbee library is for the XBee protocol and the zigpy-deconz library is for the deCONZ serial protocol.

**Comment by Adminiuga** [comment]
Renamed the PyPi package name to `bellows-homeassistant`, but keeping the existing module name to maintain compatibility with the existing codebase.
