### ISSUE TITLE
can't get this working on MATRIX creator

### ISSUE THREAD

**Issue by yoricklardenoit** [zigpy/bellows#143]
This is what i get when i try bellows form

<pre>
(bellows) pi@raspberrypi:~ $ bellows -v debug form
debug: Using selector: EpollSelector
debug: Loading application state from /home/pi/.config/bellows/app.db
debug: Sending: b'1ac038bc7e
</pre>

**Comment by Adminiuga** [comment]
You are not getting a reply on serial port to a `reset` frame. Make sure bellows is configured to use right serial port (the one connected to Silicon labs chip) and that no other process is trying to communicate over that serial.

**Comment by Hedda** [comment]
@yoricklardenoit This you solve your issue? If so then please close this (preferably with a comment on how you solved any issues).
