### ISSUE TITLE
Zigbee Sensor Error

### ISSUE THREAD

**Issue by Richdem** [zigpy/bellows#158]
I have just finishing moving all my Zigbee light bulbs from Wink Hub 2 over to HA using a GoControl HUSBZB dongle. Everything paired without any issues but I noticed for each light 2 other components were generated (see below)
![Sensor](https://user-images.githubusercontent.com/36803041/56865300-8fcd7e80-699a-11e9-865b-caebe8f7b20f.jpg)

I am getting lots of errors in the log now to do with the sensor portion of the lights. These only seem to be coming from 2 types of light, an RGB & Tuneable (soft to daylight) My standard soft lights do not have these sensors.

![Error](https://user-images.githubusercontent.com/36803041/56865304-952ac900-699a-11e9-8cb0-b4837a463f9b.jpg)

Can these sensors be disabled at all?  I am not interested in using them and would rather they not show up in the unused entity section and the log.

**Comment by dmulcahey** [comment]
We don’t poll sensors... are you using custom components?

**Comment by dmulcahey** [comment]
Also, this should be in the HomeAssistant repo... not bellows.

**Comment by Richdem** [comment]
> Also, this should be in the HomeAssistant repo... not bellows.

I am sorry,

How do I move this? 

I just paired all of my Ecosmart Zigbee bulbs with HA. The only custom component I have is a light slider. Is this what you mean

**Comment by Richdem** [comment]
How do I move this

**Comment by Richdem** [comment]
I do have a custom light slider loaded, is that what you mean?

Sorry for posting in the wrong section
