### ISSUE TITLE
Feature Request: Add network support for usb devices.

### ISSUE THREAD

**Issue by rbflurry** [zigpy/bellows#183]
I am currently trying to utilize a HUSBZB-1 connected remotely on another device in my HASSIO deployment.

It involves using ser2net to make the serial device available over the network.

```
##Zwave
3333:raw:0:/dev/ttyUSB0:115200 8DATABITS NONE 1STOPBIT
##Zigbee
3334:raw:0:/dev/ttyUSB1:57600 8DATABITS NONE 1STOPBIT
```

Typically using socat you can make a "virtual" serial device to utilize this connection 

`pty,link=/dev/ttyUSB1,raw,user=0,group=0,mode=777 tcp:IP_address:3334`

However currently there is no way to get socat running in HASSIO.

I saw that network support was added to RFXtrx (https://github.com/Danielhiversen/pyRFXtrx/pull/85)

Could the same thing be added to this library and the zwave libraries?

For reference I am using the HUSBZB-1 with https://www.gl-inet.com/products/gl-ar150/

Which has the potential to be a wifi/ethernet usb or POE powered zwave/zigbee hub. ( a wink replacement for me)

**Comment by Hedda** [comment]
@rbflurry FYI, copied your text plus idea and posted same request to zigpy @ https://github.com/zigpy/zigpy/issues/297

**Comment by rbflurry** [comment]
Thank you. I did end up getting this running with SOCAT on the Ha docker image but it is ugly.

**Comment by Adminiuga** [comment]
I wouldn't hold my breath over this happening in near future. There are two and half developers working on ZHA integration and radio libraries and frankly it is already taking more than I anticipated of the personal time. 
Also, none of the current libraries (but bellows) handle serial port disconnects/reconnects, which are more likely to happen if using serial over IP. And there could be security implications properly securing access to serial port. In other words, openly exposing your serial port to network access without any access control might not be the best idea.

I personally think if we go through the effort, then better implement something like `zigbee2mqtt` or currently being developed zwave2mqtt. I see far more potential here.

**Comment by Hedda** [comment]
@foxy82 also suggested in https://github.com/zigpy/bellows/issues/183 that one other solution could be to get socat added to HASSIO as he requested to them in https://github.com/home-assistant/docker/issues/92

As I understand it, integrated socat is what Zigbee2mqtt provides in its add-on for HASSIO, it is described from an end-users point of view here https://www.zigbee2mqtt.io/how_tos/how_to_connect_to_a_remote_adapter.html

**Comment by rbflurry** [comment]
I later found out that socat is included with home assistant now. 

You can see how I’m currently using it here. 
https://community.home-assistant.io/t/add-network-protocol-support-to-zigbee-and-zwave-integrations/136056/10

**Comment by foxy82** [comment]
Did you try the above using Hassio on docker? Sure I can run socat on the native OS however the python library that the Hassio supervisor uses to pass through serial ports to the docker filters them out. I couldn't even trick it by putting my socat port in /dev/serial-by-id

**Comment by rbflurry** [comment]
@foxy82 Yes that is what I am using now. Socat inside the hassio docker container

**Comment by Hedda** [comment]
Might be better if ZHA integration for Home Assistant Core interfaces with zigpy over MQTT or similar?

zigpy with the Zigbee database could then run on a separate Raspberry Pi, similar to Zigbee2MQTT?

If that was possible when your Zigbee network would not go down if reboot Home Assistant Core?

**Comment by Hedda** [comment]
Have you guys heard of the new Sonoff ZBBridge (Sonoff Zigbee Bridge) that was just announced?

See related request for zigpy-> https://github.com/zigpy/zigpy/issues/385

Sonoff ZBBridge is basically a prepackaged networked EmberZNet / EZSP device with an ESP8266..

**Comment by Adminiuga** [comment]
It works with latest pyserial
