### ISSUE TITLE
[SUGGESTION] Rename the bellows library and repository to "zigpy-emberznet", "zigpy-ezsp", or "zigpy-ember" for clarity and consistency

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#215]
Please rename bellows library and its repo to "zigpy-emberznet", "zigpy-ezsp", or "zigpy-ember" for clarity and consistency; to have a prefix like other zigpy radio libraries and not use an abstract name.

***EmberZNet*** is the Zigbee Protocol Stack Software that runs on EM35x and EFR32 SoC families:
- https://www.silabs.com/products/development-tools/software/emberznet-pro-zigbee-protocol-stack-software

***EZSP*** is short for "EmberZNet Serial Protocol" so is specific to protocols in EmberZNet Zigbee stack:
- https://www.silabs.com/documents/public/user-guides/ug100-ezsp-reference-guide.pdf

***Ember*** stands for the company who created EmberZNet which was latest acquired by Silicon Labs in 2011-2012:
- https://en.wikipedia.org/wiki/Ember_(company)

The specific arguments against choosing "ember" as a suffix name for this radio library for zigpy is that newer Silicon Labs today allow the newer have multiprotocol Ember series SoC chips/MCUs to run other IEEE 802.15.4 standards, such as BLE (Bluetooth Low Energy), Thread, Proprietary 2.4 GHz, as well as Zigbee 3.0

The arguments for choosing "emberznet" as a suffix name for this radio library for zigpy is that it specifically makes it clear by its name in a google search that this library is for EmberZNet PRO Zigbee Stack by Silabs.

The arguments for choosing "ezsp" instead of "emberznet" as a suffix name for this radio library for zigpy is simply that "ezsp" is shorter than "emberznet" yet still stands for "EmberZNet Serial Protocol". Problem with that name is that it as an abbreviation is not clear to understand and might not help new developers finding it if they are only searching for "EmberZNet" support.

Regardless, IMHO it would be best if the bellows lib/repository/module/project were renamed to either zigpy-emberznet", "zigpy-ezsp", or "zigpy-ember" to match the other libraries/projects related to zigpy as the others use "zigpy" prefix and 'protocol' suffix.

The name "bellows" have no official reference to the interface used, and "EmberZNet" is also a poor choice of name because it first referred to EM35x SoC platform hardware and then to the high-level API for the EmberZNet PRO stack, though the name EZSP for the APIs also stuck for the newer EFR32 family/series of SoC platform hardware from Silicon Labs.

This is only a suggestion and not a must or a showstopper in any way, but IMHO 'name branding' is important even for hobby open-source organizations that are only made up by volunteers like the zigpy organization. 

As the bellows library project is now like the other zigpy projects part of a collection of projects which are a part of an organization shared by many members and is upstream for multiple sub-projects, using the same brand name can help everyone feel that they belong to the same team who are working for the same or similar goals.

- https://github.com/zigpy

Note! This is indirectly related to the request of renaming zha-device-handlers library and repository -> https://github.com/zigpy/zha-device-handlers/issues/327 and also a request of renaming zigpy module name -> https://github.com/zigpy/zigpy/issues/351 as well as the request of renaming zigpy-xbee module name https://github.com/zigpy/zigpy-xbee/issues/96

bellows came first before broke out zigpy and newer dependencies follow same naming-standard.

There are now already all these libraries for zigpy where only "bellows" and "zha-device-handlers" do not follow the standard:

- zigpy https://github.com/zigpy/zigpy/
  - **bellows https://github.com/zigpy/bellows**
  - zigpy-cc https://github.com/zigpy/zigpy-cc
  - zigpy-deconz https://github.com/zigpy/zigpy-deconz
  - zigpy-xbee https://github.com/zigpy/zigpy-xbee
  - zigpy-zigate https://github.com/zigpy/zigpy-zigate
  - zigpy-znp https://github.com/zha-ng/zigpy-znp
  - zigpy-deconz-parser https://github.com/zha-ng/zigpy-deconz-parser
  - **zha-device-handlers https://github.com/zigpy/zha-device-handlers**

If bellows library and repo were renamed to "zigpy-emberznet" then also PyPI project can be renamed too: 

- "zigpy-emberznet" instead of "bellows-homeassistant" https://pypi.org/project/bellows-homeassistant/

I understand that the active PyPI projects being named "zigpy-homeassistant" and "bellows-homeassistant" can be confusing to new developers, especially to those who wish to use zigpy and bellows without Home Assistant as they might think that Home Assistant is a requirement for using these libraries.

Yes I have OCD but others might also find this could be a logical choice that makes total sense.

IMHO best for clarity and consistency was if both bellows and zha-device-handlers also follow the same naming-standard. 

ZHA in Home Assistant is gaining traction and zigpy will likely get more and more related libraries over time. If the "bellows" and "zha-device-handlers" libraries were renamed "zigpy-device-handlers" all would follow the same naming-standard, and I believe that more and more developers could take notice and maybe join in the development of current and future zigpy related projects,

PS: @rcloran @Adminiuga & @damarco Regardless of above it is probably also a good idea if you could and would make a few more zigpy and bellows developers shared co-owner/co-author/co-maintainers of this project on GitHub as well the package project(s) on PyPI. That could help remove some of the personal pressure on yourselves as well as explicit dependence on specific individuals. 

PPS: @rcloran @Adminiuga & @damarco I have not seen that @damarco and @AndreasBomholtz as active with zigpy related projects for quite some time, however, @Adminiuga @dmulcahey and @puddly all seem to be very active (considering these are all still just hobby projects).

**Comment by mickeprag** [comment]
Also, in the same track, why is the pypi library called "bellows-homeassistant" instead of just "bellows"? It does not have any homeassistant dependencies and can be reused by other projects as well (as I am).

I vote for a namechange from "bellows-homeassistant" to "zigpy-ezsp" (ar the author suggests).

**Comment by Hedda** [comment]
@mickeprag As I understand from https://github.com/zigpy/zigpy/issues/190 and more I read Home Assistant community forums, the reason was that @rcloran who initially created bellows (and zigpy) went missing for a long while (I'm only guessing that it was for personal reasons) before he could give more developers write access permissions to the existing projects that he has created. Anyway, the same goes for the use of "zigpy-homeassistant" (https://pypi.org/project/zigpy-homeassistant/) instead of just "zigpy" (https://pypi.org/project/zigpy/) on pypi.

You can also reas a somewhat related discussion in https://github.com/zigpy/zigpy/issues/113

**Comment by Hedda** [comment]
@rcloran any options for or against renaming bellows since you are the original creator of it & zigpy?

**Comment by Hedda** [comment]
@rcloran Would you be OK if someone else in the zigpy org renamed the bellows library & its repo?

**Comment by Hedda** [comment]
For reference, this suggestion is related and very similar to https://github.com/zigpy/zha-device-handlers/issues/327

**Comment by Hedda** [comment]
For reference, see related https://github.com/zigpy/zigpy/pull/363 in which @Adminiuga changed  zigpy module name back to just "zigpy"

**Comment by Hedda** [comment]
@Adminiuga sorry for bikeshedding but wondering how you feel about this renaming suggestion?

Apologies if my OCD ranting is not really constructive here but doesn't Parkinson's law of triviality clearly states that all bikesheds should have a corrugated galvanised iron roof and be black in colour ;)

**Comment by Hedda** [comment]
@rcloran Please let us know if you are totally against renaming bellows library, this repository on GitHub, and the PyPI project. Hope that is OK that if we do not hear from you then hope that it is OK if we will assume that you are OK with renaming them to something else with "zigpy" as the prefix.

**Comment by Hedda** [comment]
@Adminiuga OK to bump for comment/feedback on this suggestion now ;)

**Comment by roger-** [comment]
+1 for renaming.

Always wondered what this was about (until I needed it) since the name is inconsistent with everything else.

**Comment by Hedda** [comment]
@roger- Out if curiosity, what did you need it for? Troubleshooting as an end-user or developing something with it as a developer?

Mostly just thinking that it is very interesting to know of more third-party projects that use zigpy and/or bellows without HA's ZHA :)

**Comment by roger-** [comment]
@Hedda 

Actually just via ZHA (troubleshooting), but I could imagine using this for a standalone project.

**Comment by Hedda** [comment]
@roger- Maybe you would be willing to volunteer for this renaming task and submit a pull request if you would take up the task?

**Comment by Adminiuga** [comment]
At this moment we're not considering renaming `bellows`. Yes, it's name does not match zigpy and all other lib, but that's for historical reason. Zigpy came out for `bellows`. `Bellows`  was the name picked by Russel and I can't nor really want to change it. 
Renaming it won't fix anything and proper renaming, would require too many changes -- it doesn't worth it. Sorry.
