### ISSUE TITLE
[HARDWARE] DEFARO SprutStick Pro - another maker of Zigbee USB-sticks based on Silicon Labs EFR32 Series 1

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#242]
FYI, might be cool to follow this "DEFARO Zigbee Sprut Stick" project from @sprut ( sprut.ai ) by @sprut666666 as it would be nice to also have support for newer Zigbee adapters based on Silicon Labs EFR32 which uses newer SDK

Just read about their prototypes for new Ember / EmberZNet / EZSP based "DEFARO SprutStick 2" and "DEFARO SprutStick Pro" USB-sticks they are working on which will be based on an EFR32MG13P, MGM12P, or EFR32MG12 chips from the first-generation EFR32MG / EFR32MG1 family in Silicon Labs EFR32 series (EFR32MG12 Series 1 a.k.a.  Wireless Gecko Series 1 or Flex Gecko) featuring a Zigbee stack.

Updated: Final version is called "DEFARO SprutStick Pro" (based on EFR32MG12) and ships now with standard EmberZNet firmware:

- https://defaro.ru/index.php/product/89-controllers/257-sprutstick-pro

- https://spruthub.ru/stick

Perhaps @sprut / @sprut666666 be willing to donate adapters to developers of zigpy & bellows?

Made in Russia and posts are in all Russian and therefore had to use google translate to read so don't understand everything they have written about it but could be interesting for users of bellows even if the "SprutStick" is originallyy designed to be used in with "Spruthub" (Sprut.hub) which is a Russian home automation platform that relies on different USB adapters for connectivity.

https://sprut.ai/client/article/2583

https://www.instagram.com/sprut666666/

Anyway, apparently they are already testing it with Home Assistant ZHA using bellows via zigpy

https://sprut.ai/static/media/cache/00/18/44/40/2583/55648/3000x_image.jpg

https://sprut.ai/static/media/cache/00/18/44/40/2583/55649/3000x_image.jpg

https://sprut.ai/static/media/cache/00/18/44/40/2583/55663/3000x_image.jpg

Never heard about them before but apparently Defaro is a manufacturer of Zigbee & Z-Wave devices 

https://defaro.ru

**Comment by Hedda** [comment]
Also see #243 as that hardware is based on the same family and series of chip from Silicon Labs.

**Comment by Hedda** [comment]
Not sure how missed it but apparently Elelabs Zigbee USB adapter and Pi shield is based on EFR32MG1

Elelabs Zigbee Raspberry Pi Shield
- https://elelabs.com/products/elelabs-zigbee-shield.html

Elelabs Zigbee USB Adapter
- https://elelabs.com/products/elelabs-usb-adapter.html

@MattWestb stumbled on that information and posted in https://github.com/Koenkk/zigbee-herdsman/issues/168

I thought that Elelabs had not publicly published exactly which chip type they were using other than it was from Silicon Labs, so I had no idea that they are based on EFR32 MG1 (EFR32 Series 1).

I was sure that Elelabs only marketed those as alternatives Nortek GoControl QuickStick Combo Model HUSBZB-1 if you only want a Zigbee adapter compatible the bellows library as used in the ZHA integration component for Home Assistant. I know that the fact that HUSBZB-1 is not sold outside the United States was the main reason that Elelabs started making those, at least they at first have been targeting Home Assistant's ZHA users, and later also openHAB users.

Regardless Elelabs must only ship with old firmware version(s) with their products since it is compatible with the bellows library out-of-the-box and the fact is that the bellows library is currently only compatible with the older versions of EZSP protocols.

**Comment by sprut666666** [comment]
Hi, and thanks for your interest in the product.
The stick was developed for [Sprut.hub](https://spruthub.ru) and works with the latest version of SDK (the latest firmware with the latest version of SDK will always be provided)
The first batch of sticks was sold in the first 5 minutes after the start [https://spruthub.ru/stick](https://spruthub.ru/stick)
The next batch will be already large and based on the chip https://www.silabs.com/wireless/zigbee/efr32mg21-series-2-socs/device.efr32mg21a010f1024im32

**Comment by Hedda** [comment]
@sprut666666 Any chance you would consider donating series 1 and/or series 2 adapters to @Adminiuga for bellows and zigpy development?

**Comment by Adminiuga** [comment]
I appreaciate, but shipping is going to be a killer and ATM it's lack of time is the limiting factor. But once bellows supports v8, whether it is mg1 or mg2 series, to `bellows` it would be transparent.

I'd rather have someone explain me, why with the current `bellows` settings, Aqara no-neutral US wall switch, joins fine out of the box for the 1st time, but if you reset it and try to join again, it doesn't want to join. (joins and leaves). 
Still have to try it with the gateway app from Silabs, should offer some clues.

**Comment by sprut666666** [comment]
> @sprut666666 Any chance you would consider donating series 1 and/or series 2 adapters to @Adminiuga for bellows and zigpy development?
The second batch of sticks is still in production. 
And for development it is better to use the dev kit https://www.instagram.com/p/B7qswCSCrfY/ 
Moreover, now it seems you can buy for $ 99 https://www.silabs.com/development-tools/wireless/efr32xg22-wireless-starter-kit

**Comment by sprut666666** [comment]
> I appreaciate, but shipping is going to be a killer and ATM it's lack of time is the limiting factor. But once bellows supports v8, whether it is mg1 or mg2 series, to `bellows` it would be transparent.
> 
> I'd rather have someone explain me, why with the current `bellows` settings, Aqara no-neutral US wall switch, joins fine out of the box for the 1st time, but if you reset it and try to join again, it doesn't want to join. (joins and leaves).
> Still have to try it with the gateway app from Silabs, should offer some clues.

Quite right, firmware 6.7.6 globally does not differ from series to series.

I'm sorry, but I'm not using zigpy and ha. On the problem, you need to look at silabs policy and traffic zigbee sniff.
We did not notice such a problem, the Aqara no-neutral work perfectly.  List of tested equipment here https://v2.sprut.ai/catalog?tags=SprutHub

**Comment by Hedda** [comment]
@sprut666666 Which firmware are you using on SprutStick adapters? If standard EmberZNet with EZSP API firmware then can just close this as SprutStick with such firmware should be compatible with bellows and zigpy out-of-the-box without modifcations.

**Comment by sprut666666** [comment]
> @sprut666666 Which firmware are you using on SprutStick adapters? If standard EmberZNet with EZSP API firmware then can just close this as SprutStick with such firmware should be compatible with bellows and zigpy out-of-the-box without modifcations.

It's standard EmberZNet + minor edits.

**Comment by Hedda** [comment]
@sprut666666 OK so they work out-of-the-box with Home Assistant's ZHA via bellows EZSP support without firmware upgrades?

https://www.home-assistant.io/integrations/zha/

**Comment by sprut666666** [comment]
> @sprut666666 OK so they work out-of-the-box with Home Assistant's ZHA via bellows EZSP support without firmware upgrades?
> 
> https://www.home-assistant.io/integrations/zha/

If ZHA can 6.8.2.0 then yes

**Comment by Hedda** [comment]
> If ZHA can 6.8.2.0 then yes

It does support but so far 6.8.2.x has proven to be unstable and therefore 6.7.x.x is still recommended for stability in production.

**Comment by sprut666666** [comment]
> > If ZHA can 6.8.2.0 then yes
> 
> It does support but so far 6.8.2.x has proven to be unstable and therefore 6.7.x.x is still recommended for stability in production.

I didn't notice any problems other than ZLL in 6.8.2.0, on the contrary, the stability increased.

**Comment by Hedda** [comment]
As I have seen, most reports of instability with EmberZNet 6.8.x.x firmware comes from those who have hacked Sonoff ZBBridge with Tasmota and using its serial TCP server as a remote adapter with Home Assistant ZHA -> https://www.digiblur.com/2020/07/how-to-use-sonoff-zigbee-bridge-with.html

I believe that @Adminiuga is still beta testing EmberZNet 6.8.x.x firmware with bellows using Elelabs ELU013 and/or ELR023. Those adapters are both based on EFR32MG13P -> https://github.com/zha-ng/EZSP-Firmware/tree/master/Elelabs-ELU013

Elelabs themselves have not yet officially released any EmberZNet 6.8.x.x firmware updates but said back in September that they had plans to release EmberZNet 6.8.x.x firmware upgrades in October -> https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/issues/3

**Comment by sprut666666** [comment]
We have tested 6.8 since the silabs beta, we have observed that the stability has increased significantly, but ZLL 🤬🤬🤬

**Comment by MattWestb** [comment]
Thats sound bad that ZLL is going down then most users is using lights in there HA systems :-((
But the good is the overall stability is improved and hope silabs is fixing the ZLL problems i future of EZSP release.

Great feedback sprut666666 !!!

**Comment by Hedda** [comment]
@sprut666666 have you tested both upgraded and downgrading firmware on DEFARO SprutStick Pro with Elelabs EZSP Utility:

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility

Great thing about that Elelabs EZSP Firmware Update Utility is should work with all adapters using standard Silabs bootloader.

**Comment by Hedda** [comment]
@sprut / @sprut666666 FYI, "DEFARO SprutStick Pro" is now listed as zigpy/bellows compatible adapters -> https://github.com/zigpy/bellows/pull/374

**Comment by MattWestb** [comment]
@sprut666666 ZHA is starting "recommending" EZSP 6.7.8.0 after some critical bug fixes that is not implanted in 6.8 and 6.9 branch.
Is it anny plan doing one update for the first and second gen of your EFR32 1/2 ?
I can only finding 6.7.6.0 on the [download page](https://defaro.ru/index.php/firmware/258-firmware-sprutstick-pro).

And one more question on [ZHA wiki supported list](https://github.com/zigpy/zigpy/wiki/Coordinator-Firmware-Updates#recommended-firmware-version-for-ezsp-coordinators) its only on devices listed but the sprutstick-pro do have 2 hardware version. Should it being listed as 2 separate or only the new one ?
