### ISSUE TITLE
Configure Zigbee Channel from HA

### ISSUE THREAD

**Issue by meremortals70** [zigpy/bellows#271]
Hi all

New to ZHA and bellows after ditching Deconz.

Is there any possibility to add a feature on the roadmap to change the zigbee channel from either the integration or configuration in HA?

**Comment by Adminiuga** [comment]
It's on ToDo but no ETA. If you need to change channel on ConBee, just fire up deCONZ UI and change the channel then move stick back to HA

**Comment by puddly** [comment]
@meremortals70: I believe you can configure both the channel mask and the specific channel for EZSP radios within the YAML, but only during network formation: https://github.com/zigpy/zigpy/issues/154#issuecomment-635484220

**Comment by meremortals70** [comment]
Thanks @Adminiuga and @puddly
