### ISSUE TITLE
Heiman smoke sensor don't stay paired

### ISSUE THREAD

**Issue by nerdosity** [zigpy/bellows#273]
Hello, I was a long time user of Zigate on Home assistant, first with developer custom component, then with ZHA HA integration.
I tried a more mature project so I bought a Bitronvideo BV 2010/10. It almost work natively with my installation (docker container on synology).
BUT, I have two major issue:

- bigger one: my two smoke sensors stay connected just an hour. Then, after that, they drop off and they never connect again automatically.
Version is SMOK_V16. 
I don't know if they are threated as a different product, since they have the "mains" power supply (false, battery powered) and they can "scream" (but in reality it's not user controllable, they just chime when there is smoke or when the test button is pressed).
How can I help?
- smaller one (I can easily replace them): it ignores my Xiaomi temperature/humidity sensor (https://github.com/zigpy/bellows/issues/166)

https://pastebin.com/QmpKWgHv

**Comment by Adminiuga** [comment]
Yeah, heiman does not report any activity and goes into deep sleep. In reality it doesn't really goes offline, but because it is not sending any data and does not reply to the request because of the deep sleep, ZHA considers it becoming unavailable.

Do you see any data coming in when you press test button?

**Comment by nerdosity** [comment]
Yes, it became available again. But I can't trust it this way, since I don't know if it went offline or it's just in standby.

**Comment by Adminiuga** [comment]
You won't be able to tell. Yes, they will be available in HA but if it really goes offline it still going to be online in zha. I'd recommend against this sensor. Alternatively, ask heinman to update firmware
