### ISSUE TITLE
[REQUEST] Ability to upgrade Silicon Labs Zigbee coordinator firmware via bellows and ZHA GUI?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#289]
This is a feature request for the ability to upgrade Silicon Labs Zigbee coordinator firmware via bellows and/or ZHA GUI.

Suggest considering adding the ability to upgrade Silicon Labs Zigbee coordinator firmware via bellows commands.

In addition, it would be great if could backup and restore  EFR32 firmware if possible.

It would also be very user-friendly if EFR32 firmware updates could be done via bellows and Home Assistant ZHA user interface.

@Adminiuga @dmulcahey Requesting this now as @@NilsBohr from Elelabs posted in https://github.com/zigpy/bellows/issues/243 saying that he/they released an open source Python script utility that can update the firmware via Silicon Labs serial bootloader protocol that could potentially work on many different Silicon Labs Zigbee chips.

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility

Would be awesome for bellows and Home Assistant users if ZHA GUI could use bellows and this Elelabs utility script to update the firmware on their Silicon Labs based adapters.

PS: FYI @puddly had implemented similar firmware update feature ability into zigpy-znp for Texas Instruments chips, see:

https://github.com/zha-ng/zigpy-znp/issues/24

Best would probably be if users could have this ability if only they first manually download and rename firmware binary image file in a specific format to a predetermined file-name and then place that correctly formatted/named file in a specific directory before being able to issue an "upgrade coordinator firmware" command.

If so it would probably be best to first let the user manually download and unpack the firmware themselves so leave the responsibility to them to make sure it is in the correct format and then having a button in the ZHA UI for "upgrade coordinator firmware".

More user-friendly would then, of course, be if ZHA let you enter a URL source location for automatic download of firmware.

**Comment by Adminiuga** [comment]
Zigpy-znp uses a separate flashing utility. Bellows already have 'bootloader' cli option which puts it into boot mode and you can update it using any serial terminal
