### ISSUE TITLE
Migrate asynctest to stdlib's AsyncMock

### ISSUE THREAD

**Issue by fabaff** [zigpy/bellows#339]
Asynctest doesn't work with Python 3.8 and above. It's the same issue as for zigpy (https://github.com/zigpy/zigpy/issues/475).

**Comment by Hedda** [comment]
@Adminiuga @puddly same with zigpy-znp too?  

https://github.com/zha-ng/zigpy-znp/ 

Any other radio libraries for zigpy?

**Comment by Adminiuga** [comment]
Fixed in #350
