### ISSUE TITLE
[DEPENDENCY] Bump version of zigpy in bellows setup.py on GitHub to syncup with zigpy?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#341]
@Adminiuga Currently bellows setup on GitHub require only "zigpy>=0.20.1a3" version?

https://github.com/zigpy/bellows/blob/master/setup.py

https://github.com/zigpy/bellows/blob/dev/setup.py

**Comment by Adminiuga** [comment]
Fixed in https://github.com/zigpy/bellows/commit/a0ac1b3aba1c6bc9b7b837bd62e4f2b466f73439
