### ISSUE TITLE
[COMPATIBILITY] Cortet ZM3588S-USB or ZM357S-USB EM35x USB Sticks by CEL?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#351]
Anyone tested if these "Cortet" EM3588 / EM357 based radios from CEL are compatible with bellows (EZSP) out-of-the-box?

"MeshConnect" EM35x based USB sticks/dongles/adapters in the "Cortet" series by CEL (California Eastern Laboratories):

***CEL Cortet ZM3588S-USB (EM3588 / EM358x Zigbee chip by Silicon Labs)***

***CEL Cortet ZM357S-USB (EM357 / EM357x Zigbee chip by Silicon Lab)*** 

Also, they have matching +20dBm models in LR (long-range) versions however they had some hint that may ship Thread firmware:

***CEL Cortet ZM3588S-USB-LR (EM3588 / EM358x Zigbee chip by Silicon Lab)***

***CEL Cortet ZM357S-USB-LR (EM357 / EM357x Zigbee chip by Silicon Lab)*** 

![image](https://user-images.githubusercontent.com/6320001/116854337-d6908780-abf7-11eb-9f3f-10465134fc14.png)

If they do not work out-of-the-box has anyone tried to flash them with newer Silabs EmberZNet firmware to upgrade them?

They are not very expensive today and seem to be sold all around the world by quite a lot of major electronics distributors. 

The official Ember documentation from CEL says they support Silicon Labs EmberZNet PRO ZigBee stack and serial interface:

http://www.cel.com/pdf/datasheets/EM357_USB_Sticks_DS.pdf

http://www.cel.com/product.do?command=viewOverview&group=6

https://github.com/zigpy/zigpy/files/6409608/3388832429388690em357_usb_sticks_ds.pdf

I'm not asking for buying advice as already have adapters but only requesting info for bellows and ZHA compatibility lists:

https://www.home-assistant.io/integrations/zha/

PS: I first found out about these reading the OpenHAB Supported Coordinators under their ZigBee Binding documentation:

https://www.openhab.org/addons/bindings/zigbee/

"**_57600bps 
Software flow control 
High RAM_**"

**Comment by Hedda** [comment]
@walthowd Do you think these adapters could also be updated with your firmware updater image for Zigbee coordinators? 

https://github.com/walthowd/husbzb-firmware

Just a curious question as I do not actually own any of those myself and do not plan on buying them, nor recommend them.

**Comment by walthowd** [comment]
I'm not sure -- It appears the `ncp.py` I have adapted and updated from Silicon Labs to query and load the firmware was originally written for CEL sticks, so I would hazard a guess it would work -- but someone would still need to test.

**Comment by Hedda** [comment]
FYI, grobasoz tested his firmware image compiled EM3581 on a another EM3588 based adapter he had and it worked for him:

https://github.com/grobasoz/zigbee-firmware

https://github.com/walthowd/husbzb-firmware/

https://github.com/Elelabs/elelabs-zigbee-ezsp-utility/
