### ISSUE TITLE
[REQUEST] Probe method feature with automatically probing of first 115200 baud rate and then 57600 baud rate?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#396]
Follow-up from discussion in https://github.com/walthowd/husbzb-firmware/issues/12

Feature request to please consider extending the zigpy/bellows probe method feature with an automatic probing function for speed that first try probe with 115200 baud rate speed and then also try to probe 57600 baud rate speed but only if 115200 baud rate fail?

Reason for this request is that auto set baud rate would make the initial installation config flow in ZHA even more user-friendly.

Many updated/newer EmberZNet NCP firmware support 57600 baud rate speeds, and that will reportedly soon also include at least Silicon Labs EmberZNet Zigbee NCP v6.7.8 firmware that will ship several upcoming relativly inexpensive EFR32MG13 and EFR32MG21 based "Zigbee 3.0 dongle" that ITead and others will soon start selling.

PS: By the way, bellows test code looks to use 115200 by default -> https://github.com/zigpy/bellows/blob/dev/tests/test_ezsp.py

**Comment by Hedda** [comment]
Perhaps this request/suggestion should maybe be moved to zigpy issues at https://github.com/zigpy/zigpy/issues instead?

**Comment by Adminiuga** [comment]
Submit PR.

**Comment by pipiche38** [comment]
https://github.com/zigpy/bellows/pull/480
