### ISSUE TITLE
Support for multiple restore from backup could be prevented in adapter firmware?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#414]
Is it true that Elelabs adapters only allow a single restore from backup and if so should a warning be added to readme? 

https://github.com/zigpy/bellows#nvram-backup-and-restore

See this Jeedom blog post by (translated from French to English with Google):

https://blog.jeedom.com/5183-tout-ce-quil-faut-savoir-sur-le-plugin-officiel-zigbee/

"_This backup can be restored on another controller of the same type. **Be careful, however, some types of controllers such as EZSP Elelabs only accept a single restoration procedure during their entire life .**_"

@zoic21 do you know anything more about this?

**Comment by MattWestb** [comment]
It the normal thing with all EFR32 and EM35X devices.
You can writing in token on time then you need doing on chip erase (or the specific flash page) and you can writing on new token.

If you is having on SWD flasher is no problems but for normal user is on one time operation.

**Comment by Adminiuga** [comment]
https://media.giphy.com/media/SVgKToBLI6S6DUye1Y/giphy.gif

You can restore backup as many times as you want. You can override EUI64 only once, unless you have a jlink
