### ISSUE TITLE
Secure EZSP Protocol (Secure EZSP) interface support option in bellows?

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#448]
Does bellows have the option to support Secure EZSP Protocol (Secure EmberZNet Serial Protocol) interface support in bellows?

"_The Secure EZSP Protocol (Secure EZSP) is an optional protocol that encrypts communications between the Host and NCP_":

https://www.silabs.com/documents/public/application-notes/an1125-creating-and-using-a-secure-ezsp-host-to-ncp-interface.pdf

Thinking encrypted communications be nice as an option when using a remote network-attached Zigbee coordinator via socat?

**Comment by Adminiuga** [comment]
Yes, it can be added once you submit the PR.
