### ISSUE TITLE
Enhancement: dump to stdout

### ISSUE THREAD

**Issue by AndrewFromMelbourne** [zigpy/bellows#503]
Would it be possible to allow "dump" to send the output to stdout? This would be useful as it then would be possible to stream the packets into Wireshark for analysis.

This may be already possible, but I couldn't figure it out.

Thanks,

Andrew.

**Comment by MattWestb** [comment]
Last time i was testing it was working OK.
https://github.com/zigpy/zigpy/discussions/692

But for sniffing from windows with  USB i normally using https://github.com/zsmartsystems/com.zsmartsystems.zigbee.sniffer.

**Comment by AndrewFromMelbourne** [comment]
Thanks @MattWestb, Didn't think of "-w /dev/stdout" works for me on MacOS.
