### ISSUE TITLE
Zigbee Error EmberStatus.MAX_MESSAGE_LIMIT_REACHED

### ISSUE THREAD

**Issue by SolutionSoftwareMaexx** [zigpy/bellows#522]
Hello, I have problems with my zigbee integration.
The error EmberStatus.MAX_MESSAGE_LIMIT_REACHED is triggered when I want to set the temperature at my thermostat. At the beginning it works, but after 1-2 days I get the error message. After a restart everything works again.

Here is a link to the discussion
https://github.com/zigpy/zha-device-handlers/issues/1818#issuecomment-1399240127

And I have also attached a log file.

I hope you can help me.

Greeting Mäxx

[error_log.txt](https://github.com/zigpy/bellows/files/10472589/error_log.txt)

**Comment by puddly** [comment]
I believe this has been fixed with https://github.com/NabuCasa/silabs-firmware-builder/pull/71. If you use a SkyConnect or Yellow, update the firmware to the latest version.
