### ISSUE TITLE
Is there a way to assess the zigbee mesh connectivity via the bellows cli?

### ISSUE THREAD

**Issue by wixoff** [zigpy/bellows#59]
I'm using Home Assistant and recently replaced my Osram Lightify bridge with the HUSBZB-1 stick, which works great for the most part.  However, the Lightify bridge was near the center of the house (and was extremely reliable), and my PC with the USB stick is in a corner office.  So now I'm seeing poor connectivity with some of the bulbs at the opposite end of the house.  I have to switch them several times to get them to actually turn on/off.  This is not entirely surprising, since bulbs (and I'm using a mixture of GE Link, Osram/Sylvania, and IKEA Tradfri) are not known as reliable repeaters.

So I picked up an Iris Smart Plug from Lowe's which is supposed to work well as a repeater (at least according to the SmartThings folks) and placed it between the USB stick and the unreliable bulbs.  I pulled out my HUSBZB-1 stick for 20 minutes to see if the mesh would reorganize itself, but I'm still not seeing good results.  The Smart Plug itself is reachable and quite reliable, and is only 15-20 feet (no walls) from the unreliable bulbs.

Is there a way I can see if the Smart Plug is actually part of the routing table for these bulbs?  And if I can see that it's not, is there a way to force it to talk to them?

Thanks!

**Comment by rcloran** [comment]
There is no way to do it at the moment. EZSP does expose some of that information.
