### ISSUE TITLE
'bellows devices' CLI crashes with AttributeError: 'Ledvance' object has no attribute 'get'

### ISSUE THREAD

**Issue by jcoe2412** [zigpy/bellows#650]
when using 'bellows devices' on my raspberry PI , I get the following error :

  File "/home/jcoe2412/zigbee/python-venv2/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 779, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/home/jcoe2412/zigbee/python-venv2/lib/python3.11/site-packages/zigpy/config/validators.py", line 124, in cv_ota_provider
    provider_type = obj.get(zigpy.config.CONF_OTA_PROVIDER_TYPE)
                    ^^^^^^^
AttributeError: 'Ledvance' object has no attribute 'get'

Any idea how to fi this ?

**Comment by puddly** [comment]
The bellows CLI is somewhat deprecated. This specific command isn't bellows-specific, do you think you could make a PR to the zigpy-cli repo and add it?

**Comment by jcoe2412** [comment]
I finally installed Zigbee2MQTT as this was much easier to put in place....thanks for your support
