### ISSUE TITLE
how to run  "bellows" in "windows" 

### ISSUE THREAD

**Issue by amosrohe** [zigpy/bellows#655]
hi
I am trying to run  "bellows" in "windows" 
when i run 

bellows --device com7
I get "Error: Missing command"

bellows --device
i get "Error: Option '--device' requires an argument." 

what is the argument required in windows on Linux it is "/dev/ttyUSB1"

tnx

**Comment by TheJulianJES** [comment]
Something like `bellows -d COM7 info` should work.
However, it's recommended to use [zigpy-cli](https://github.com/zigpy/zigpy-cli) instead of the integrated bellows CLI, as it's not really maintained anymore.
