### ISSUE TITLE
Bulk reading capability

### ISSUE THREAD

**Issue by bojanrajkovic** [zigpy/bellows#72]
For example, I would love to be able to bulk read devices by specifying some sort of file (YAML?) that includes the target host, the endpoint ID, cluster ID, and attribute to read.

The per-run startup costs of doing these reads one host/endpoint/cluster/attribute at a time, especially on a slow device (RPi or similar) are pretty high. I suspect this is due to both Python runtime startup/teardown costs, and UART/ZigBee setup costs.

Doing it "naively" (ie. spawn bellows for each 4-tuple) takes almost 2 minutes on my RPi, but by applying [this hack][hack] to the Bellows CLI, I can get it down to 21 seconds, and I get all my data at once.

UPDATE: A daemon mode or something like it would also be great. :) I want to poll some sensors occasionally (2-3 minutes), and push the data to InfluxDB, but couldn't figure out how to use Bellows from a Python script.

[hack]: https://gist.github.com/bojanrajkovic/20225f1060181c79f8859662ea2c08bb

**Comment by rcloran** [comment]
Bellows is a library. That means it's designed to write code against. The CLI was a convenience during development (as I'm sure you can tell by the inconsistency of output etc), and not designed to be automated with. Write code against bellows/zigpy.
