### ISSUE TITLE
INNR E14 Bulbs

### ISSUE THREAD

**Issue by sysrun** [zigpy/bellows#77]
Hi, i am trying to controll INNR E14 Bulbs with Home Assistant 58.1

The Lamp is included into HA and there is a Switch - but thats it. No control possible. The HA logs are giving me no information (even in debug mode) - no errors, just the switch calls.

Is it possible to debug the whole setup somehow? Bellows commandline?

**Comment by rcloran** [comment]
Yes, the bellows commandline is one way that you may be able to get more information.
