### ISSUE TITLE
cc2530 on serial0 

### ISSUE THREAD

**Issue by passie** [zigpy/bellows#84]
Not a issue perse, though needed some clarification. 
I have connected a cc2530 on gpio 14 & 15 and can't get this to work with bellows.
What's needed in order for bellows to talk to the attached cc2530 device ?
reading your comment's on your pr from.
[https://github.com/home-assistant/home-assistant/pull/6263](url)
it should be possible to extend this module with cc2530 knowledge.

Any advice is welcome.
regards,
Passie

**Comment by rcloran** [comment]
bellows doesn't support this type of radio. zigpy is the zigbee part of bellows split out. It should be possible to implement the radio interface and re-use zigpy.
