### ISSUE TITLE
Invite more developers to join "Team Bellows" working in upstream repo? 

### ISSUE THREAD

**Issue by Hedda** [zigpy/bellows#90]
@rcloran & @AndreasBomholtz Can I suggest that you extend some invitations to a few more developers who are already actively working on patches for and forks of bellows to join some kind of "Team Bellows" which could work together to achieve common goals for the upstream bellows repository? As a team you could collaborate using a common chat and/or forum as communication channel(s) for sharing ideas and discussing short-term and long-term goals for bellows?

To start with some example team-member candidates of the people who looks to be actively been working on improvements and enhancements for bellows and zha for Home Assistant are; @Yoda-x @dmulcahey @jonatanolofsson @damarco @Seluxit @h3ndrik @SteveEasley @titilambert @puddly

Having a team collaborating would off-load some of the work from you. Like if you and a few of them are willing to work together as team then you could for example all help review and give feedback on each other’s pull request for patches and once trust is proved you could giving more people write access to the upstream bellows repository to assist in committing push request and fixing issues that other people posts?

Long-term, do you believe that it would be a good or bad idea to have more people with write access to your upstream bellows repo?

**Comment by jonatanolofsson** [comment]
@rcloran I see you are in the process of breaking out the zigbee parts from the ezsp parts of bellows into a new project. While I commend the effort and separation, I would - from experience - advise to keep those in the same repository and instead later add more devices/low-level protocols in bellows. Splitting introduces a lot of overhead in versioning and interface compatibility problems (source: I was previously a Software Configuration Manager consultant). I think this is a very useful piece of software, and if you would like to discuss architecture and changes, I for one could contribute with my opinions, e.g. over at the discord chat: https://discord.gg/D5dRgXQ
